name: 'sugar_mate'
description: "A new Flutter project template."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  local_auth_platform_interface: ^1.0.10
  flutter_bloc: ^9.0.0
  sizer: ^3.0.5
  package_info_plus: ^8.3.0
  local_auth: ^2.3.0
  local_auth_android: ^1.0.46
  local_auth_darwin: ^1.4.3
  shared_preferences: ^2.5.2
  bloc: ^9.0.0
  connectivity_plus: ^6.1.3
  device_info_plus: ^11.4.0
  permission_handler: ^11.4.0
  get_it: ^8.0.3
  flutter_udid: ^4.0.0
  flutter_secure_storage: ^9.2.4
  equatable: ^2.0.7
  dartz: ^0.10.1
  intl: ^0.19.0
  lottie: ^3.3.1
  carousel_slider: ^5.0.0
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_analytics: ^11.4.4
  firebase_crashlytics: ^4.3.4
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  flutter_image_compress: ^2.1.0
  path: ^1.8.3
  tflite_flutter: ^0.11.0
  image_cropper: ^9.1.0

dependency_overrides:
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/lottie/
    - assets/images/
    - assets/models/diabetes_model.tflite
#    - assets/images/jpg/

#  fonts:
#    - family: Poppins
#      fonts:
#        - asset: assets/fonts/poppins/Poppins-Thin.ttf
#          weight: 100
#        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
#          weight: 200
#        - asset: assets/fonts/poppins/Poppins-Light.ttf
#          weight: 300
#        - asset: assets/fonts/poppins/Poppins-Regular.ttf
#          weight: 400
#        - asset: assets/fonts/poppins/Poppins-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
#          weight: 600
#        - asset: assets/fonts/poppins/Poppins-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
#          weight: 800
#        - asset: assets/fonts/poppins/Poppins-Black.ttf
#          weight: 900
#
#    - family: Lato
#      fonts:
#        - asset: assets/fonts/lato/Lato-Thin.ttf
#          weight: 100
#        - asset: assets/fonts/lato/Lato-Light.ttf
#          weight: 300
#        - asset: assets/fonts/lato/Lato-Regular.ttf
#          weight: 400
#        - asset: assets/fonts/lato/Lato-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/lato/Lato-Black.ttf
#          weight: 900
